[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "dist/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "discord.js"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[[headers]]
  for = "/_astro/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[dev]
  framework = "astro"
  targetPort = 4321