[build]
  command = "pnpm run build"
  publish = "dist/client"
  functions = "dist/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "discord.js"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[dev]
  framework = "astro"
  targetPort = 4321